services:
  server:
    container_name: dhimahi-server
    image: dhimahi-server
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/var/www/html/
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    container_name: dhimahi-db
    image: mariadb:11
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - MARIADB_ROOT_PASSWORD=pasWooRd#
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/db.sql:/docker-entrypoint-initdb.d/db.sql

volumes:
  mysql-data: